<a href="https://colab.research.google.com/github/FredMunene/Data-Analysis-With-Python/blob/main/Fundamentals_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy enables scientific computing and high perfomance tasks execution with multi-dimensional or n-dimensional arrays.

In [ ]:
import numpy as np
from timeit import Timer #Timer module for calculating time scripts take to run

In [ ]:
size_of_vec = 10000  #specifies numbers inrange of 0-9999
X_list = range(size_of_vec)
Y_list = range(size_of_vec)
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)


In [ ]:
def list_version(): #Based on using lists
  Z = []
  for i in range (len(X_list)):
    Z.append(X_list[i] + Y_list[i])


In [ ]:
def numpy_version():#Based on Numpy 
   Z = X + Y


In [ ]:
timer_obj1 = Timer ("list_version()", "from __main__ import list_version")
timer_obj2 = Timer ("numpy_version()", "from __main__ import numpy_version")

print("list version : ", timer_obj1.timeit(10))
print("numpy version : ", timer_obj2.timeit(10))

list version :  0.04408747900004073
numpy version :  0.0035764149999977235


  Array - collection of ordered elements of same data type.

Vector - O1 dimension array

N-dimension

Matrix- Rows and columns

m x n array of scalars . Individual values are called entries. rows X columns

NUmerical Python(Numpy)
> For multi-dimensional arrays


Shape of Matrix = the number of dimensions. 

**Creating Numpy Array from Python List**

In [ ]:
heights = [14,23,34,35,36,37]

heights_np = np.array((heights)) #one-dimesnional array
print(type(heights))
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
weights = np.array([[40,41,42,43],[50,51,52,53],[60,61,62,63],[70,71,72,73],[80,81,82,83],[90,91,92,94]])
print(weights)


[[40 41 42 43]
 [50 51 52 53]
 [60 61 62 63]
 [70 71 72 73]
 [80 81 82 83]
 [90 91 92 94]]


Attributes of ndarray objects.
1.ndim : no. of dimensions of array
2.shape : (number_rowa, number_columns)
3.size : total no. of elements
4. dtypes : type of data
5. stries : no. of bytes tht are moved tostore each row abd column in memory (no_bytes_files,no_bytes_columns)

In [ ]:
print("dimension: ", weights.ndim)
print("shape: ",weights.shape)
print("size: ",weights.size)
print("dtype: ",weights.dtype)
print("strides: ",weights.strides)


dimension:  2
shape:  (6, 4)
size:  24
dtype:  int64
strides:  (32, 8)


dimension:  2  >two-dimensional array
shape:  (6, 4)
size:  24
dtype:  int64
strides:  (32, 8)

Functions of numpy arrays

In [ ]:
xx = np.zeros(shape=(3,4), dtype ="int32") #a zero-array
print(xx)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
x = np.arange(start=100, stop=110, step=1) # i inclusive, j exclusive
print(x)

[100 101 102 103 104 105 106 107 108 109]


In [ ]:
x_lin = np.linspace(start=10, stop=50, num=30) #array of "n" values in total. equal magnitude
print(x_lin)

[10.         11.37931034 12.75862069 14.13793103 15.51724138 16.89655172
 18.27586207 19.65517241 21.03448276 22.4137931  23.79310345 25.17241379
 26.55172414 27.93103448 29.31034483 30.68965517 32.06896552 33.44827586
 34.82758621 36.20689655 37.5862069  38.96551724 40.34482759 41.72413793
 43.10344828 44.48275862 45.86206897 47.24137931 48.62068966 50.        ]


In [ ]:
x_ful = np.full(shape=(5,6), fill_value=3) # all values are "f"
print(x_ful)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


Reshaping an array

In [ ]:
print(weights.shape)
print(weights)

In [ ]:
weights1 = weights.reshape((4,6)) # values distributed fromleft-to-right then top-to-bottom
print(weights1)

In [ ]:
weights2 = weights.reshape((2,6,2))
print(weights2)

[[[40 41]
  [42 43]
  [50 51]
  [52 53]
  [60 61]
  [62 63]]

 [[70 71]
  [72 73]
  [80 81]
  [82 83]
  [90 91]
  [92 94]]]


In [ ]:
weights_flattened = weights.flatten() #elements re-organized into one-dimensional array
weights_flattened

array([40, 41, 42, 43, 50, 51, 52, 53, 60, 61, 62, 63, 70, 71, 72, 73, 80,
       81, 82, 83, 90, 91, 92, 94])

Create an array of 51 elements starting at 100 and ending at 500, using the two functions np.linspace() and np.arange(). Arrays must have the same content, with the names array_lin and array_ara, respectively. Verify that the arrays have the same content with the np.array_equal() function.

In [ ]:
array_lin = np.linspace(start =100,stop = 501,num =51)
array_ara = np.arange(start =100,stop = 501.01,step =8.02)
print(array_lin)
print(array_ara)
print(np.array_equal(array_ara,array_lin))

Array Indexing

First element - Index '0'

In [ ]:
weights

In [ ]:
weights1

In [ ]:
weights2

array([[[40, 41],
        [42, 43],
        [50, 51],
        [52, 53],
        [60, 61],
        [62, 63]],

       [[70, 71],
        [72, 73],
        [80, 81],
        [82, 83],
        [90, 91],
        [92, 94]]])

In [ ]:
heights_np

In [ ]:
print(weights2[1][3])

[82 83]


In [ ]:
weights

array([[40, 41, 42, 43],
       [50, 51, 52, 53],
       [60, 61, 62, 63],
       [70, 71, 72, 73],
       [80, 81, 82, 83],
       [90, 91, 92, 94]])

In [ ]:
weights[:2,::2]

array([[40, 42],
       [50, 52]])

In [ ]:
weights2
weights2[:3,:3,:1]

array([[[40],
        [42],
        [50]],

       [[70],
        [72],
        [80]]])

Using negative index intervals

In [ ]:
heights_np

**Arithmetic** **Operations**

np.add(array1,array2)

np.substract()

np.multiply()

np.divide()

**Logical** **Operations**

np.logical_or()

np.logical_and()

np.logical_not()

**Comparison** -**Relational** **operators** 

np.equal()               
np.not_equal()                
np.less_equal()


**Brodcasting**